# Generated by Django 2.2.5 on 2019-10-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testserver_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigationquestions',
            name='selectionA',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='investigationquestions',
            name='selectionB',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='investigationquestions',
            name='selectionC',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='investigationquestions',
            name='selectionD',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='investigationquestions',
            name='selectionE',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='investigationquestions',
            name='selectionF',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='investigationquestions',
            name='selectionG',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='investigationquestions',
            name='selectionH',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='investigationquestions',
            name='selectionI',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='investigationquestions',
            name='selectionJ',
            field=models.TextField(default=''),
        ),
    ]
