# Generated by Django 2.2.5 on 2019-10-20 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testserver_test', '0002_auto_20191019_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('filename', models.CharField(default='', max_length=252)),
                ('file_md5', models.CharField(max_length=128)),
                ('file_type', models.CharField(max_length=32)),
                ('file_size', models.IntegerField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': '图片',
                'db_table': 'upload_image',
            },
        ),
    ]
