# Generated by Django 2.2.5 on 2019-10-22 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testserver_test', '0003_uploadimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='themeid',
            new_name='type',
        ),
    ]
