# Generated by Django 2.2.5 on 2019-10-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testserver_test', '0004_auto_20191022_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investigationquestions',
            name='themeid',
        ),
        migrations.AlterField(
            model_name='investigationquestions',
            name='type',
            field=models.TextField(default='null', max_length=30),
        ),
    ]
