# Generated by Django 2.2.5 on 2019-10-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testserver_test', '0005_auto_20191022_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='problem1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='survey',
            name='problem2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='survey',
            name='problem3',
            field=models.TextField(default=''),
        ),
    ]
