# Generated by Django 2.2.5 on 2019-10-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testserver_test', '0006_auto_20191027_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='problemOffset',
            field=models.TextField(default=0),
        ),
    ]
